/*
 * Copyright (c) 2014. Needham Software LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.solrsystem.gui;

import org.solrsystem.DownloadStatusListener;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DownloadProgress extends JDialog implements DownloadStatusListener {
  private JPanel contentPane;
  private JProgressBar progressBar;
  private JLabel progressLabel;

  public DownloadProgress(String title) {
    setTitle(title);
    setContentPane(contentPane);
    setModal(false);
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
  }


  @Override
  public int progressInterval() {
    return 1024*10;
  }

  @Override
  public void onProgress(long bytesRead, long totalnum) {
    int barLength;
    int barPos;
    if (totalnum > Integer.MAX_VALUE) {
      double scaleFactor = (totalnum / (double) Integer.MAX_VALUE);
      double bytesR = bytesRead / scaleFactor;
      barLength = Integer.MAX_VALUE;
      barPos = (int) Math.round(bytesR);
    } else {
      barLength = (int) totalnum;
      barPos = (int) bytesRead;
    }
    progressBar.setMinimum(0);
    progressBar.setMaximum(barLength);
    progressBar.setValue(barPos);
    if (bytesRead == totalnum) {
      this.setVisible(false);
      this.dispose();
    } else {
      if (!this.isVisible()) {
        this.pack();
        this.setLocationRelativeTo( null );
        this.setVisible(true);
      }
    }
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPane = new JPanel();
    contentPane.setLayout(new BorderLayout(0, 0));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(2, 2));
    contentPane.add(panel1, BorderLayout.CENTER);
    panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(panel1.getFont().getName(), panel1.getFont().getStyle(), panel1.getFont().getSize())));
    progressLabel = new JLabel();
    progressLabel.setText("Download Progress");
    panel1.add(progressLabel, BorderLayout.NORTH);
    progressBar = new JProgressBar();
    panel1.add(progressBar, BorderLayout.CENTER);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPane;
  }
}
