= Solr Ref Guide Indexer

This is an example of how to adapt the shakespeare example to another use case.
Typing out this README was the majority of the time required to construct this example.
Without the time to document this for you indexing the solr ref guide with JesterJ took about 15-20 minutes (excluding time to run the solr build to create a local copy of the ref guide. The solr build takes almost as long as configuring JesterJ!).

NOTE:  This is meant to demonstrate the ease of **getting started using JesterJ ** but an astute observer will note that there is plenty of work to do to improve the results.
Most obviously, the <nav> element on every page pollutes the relevancy of any word used in the navigation menu, and images are indexed which is of debatable utility.


== Steps:

1. Checkout solr
1. build ref guide
+
[source,bash]
----
./gradlew :solr:solr-ref-guide:buildLocalSite
----

1. Then in SolrRefguideConfig paste the absolute path to /solr/solr/solr-ref-guide/build/site into
+
[source,java]
----
File refGuideAbsoluteLocation = new File("YOUR__PATH__HERE");
----

1. Adjust zookeepr settings here:
+
[source, java]
----
sendToSolrBuilder
    .named("solr_sender")
    .withProcessor(
        new SendToSolrCloudProcessor.Builder()
            .named("solr_processor")
            .withZookeeper("YOUR_ZK:2181/ZK_ROOT_IF_APPLICABLE")
----

Now follow the instructions for build & run at `code/examples/shakespeare/README.md`

The steps above are the key bits, below is a full diff from my local machine including the niceties of renaming stuff

[sourc,diff]
----
Index: code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/ShakespeareConfig.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/ShakespeareConfig.java b/code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/SolrRefguideConfig.java
rename from code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/ShakespeareConfig.java
rename to code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/SolrRefguideConfig.java
--- a/code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/ShakespeareConfig.java
+++ b/code/examples/ref-guide/src/main/java/org/jesterj/example/shakespeare/SolrRefguideConfig.java	(date 1708116398975)
@@ -14,7 +14,7 @@
 import java.io.File;

 @JavaPlanConfig
-public class ShakespeareConfig implements PlanProvider {
+public class SolrRefguideConfig implements PlanProvider {

   // First declare some constants for legibility and convenience (none required)
   private static final String ACCESSED = "format_accessed_date";
@@ -22,7 +22,7 @@
   private static final String MODIFIED = "format_modified_date";
   private static final String SIZE_TO_INT = "size_to_int_step";
   private static final String TIKA = "tika_step";
-  private static final String SHAKESPEARE = "Shakespeare_scanner";
+  private static final String SCANNER = "file_scanner";

   public Plan getPlan() {

@@ -40,7 +40,7 @@

     // If you have things to declare/create that will be used in configuration get it out of the way
     // here to keep the config concise.
-    File testDocs = new File("data");
+    File refGuideAbsoluteLocation = new File("/home/gus/projects/gus-asf/solr/fork/solr/solr/solr-ref-guide/build/site/solr/latest");

     //
     // This is the first important part. Each step needs to be configured. Order is NOT important, but I find it
@@ -49,11 +49,11 @@

     // Our initial source of documents, note the use of testDocs defined above to keep this legible
     scanner
-        .named(SHAKESPEARE) // everything should be given a unique name composed of alphanumerics and underscores only.
-        .withRoot(testDocs)
+        .named(SCANNER) // everything should be given a unique name composed of alphanumerics and underscores only.
+        .withRoot(refGuideAbsoluteLocation)
         .rememberScannedIds(true)
         .detectChangesViaHashing(true)
-        .scanFreqMS(1000);
+        .scanFreqMS(60000);

     // format the several dates produced by the scanner (to the default ISO output, solr wants)
     formatCreated
@@ -116,8 +116,8 @@
         .withProcessor(
             new SendToSolrCloudProcessor.Builder()
                 .named("solr_processor")
-                .withZookeeper("localhost:9983")
-                .usingCollection("jjtest")
+                .withZookeeper("localhost:2181/solr__home_gus_projects_gus-asf_solr_fork_testing_2024-02-12")
+                .usingCollection("ref_guide")
                 .placingTextContentIn("_text_")
                 .withDocFieldsIn(".fields")
                 .sendingBatchesOf(20)
@@ -136,7 +136,7 @@

         // arguments: Builder for step, NAME of any predecessor steps. THIS is why all steps must be
         // named and all names must be unique. You will get an error if you have duplicate names.
-        .addStep(formatCreated, SHAKESPEARE)
+        .addStep(formatCreated, SCANNER)
         .addStep(formatModified, CREATED)
         .addStep(formatAccessed, MODIFIED)
         .addStep(renameFileSizeToInteger, ACCESSED)

----