# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 */3 * *

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./code/ingest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}
    - name: Build with Gradle
      run: ./gradlew jacocoTestReport
      working-directory: ${{env.working-directory}}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          files: code/ingest/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
    - name: Submit Dependencies
      uses: mikepenz/gradle-dependency-submission@v0.8.3
      with:
        gradle-project-path: "code/ingest"
        gradle-build-module: ":"
        gradle-build-configuration: "unoJarPack"
